version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xe9s2bd0obh9"
s3_prefix = "dev"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
