AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SportsbookBFF

Parameters:
  AuthKey:
    Description: 'API Key'
    Type: 'String'
    NoEcho: true
  TlaApiKey:
    Description: 'TLA API Key'
    Type: 'String'
    NoEcho: true
  ScanBaseUrl:
    Description: 'SCAN Base URL'
    Type: 'String'
  SmpBaseUrl:
    Description: 'SMP Base URL'
    Type: 'String'
  CmsApiKey:
    Description: 'CMS API Key'
    Type: 'String'
    NoEcho: true
  CmsBaseUrl:
    Description: 'CMS Base URL'
    Type: 'String'

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        AUTH_KEY: !Ref AuthKey
        TLA_API_KEY: !Ref TlaApiKey
        SCAN_BASE_URL: !Ref ScanBaseUrl
        SMP_BASE_URL: !Ref SmpBaseUrl
        CMS_API_KEY: !Ref CmsApiKey
        CMS_BASE_URL: !Ref CmsBaseUrl

Resources:
  APIGateway:
    Type: AWS::Serverless::HttpApi

  SportsbookBFFLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .build/lambda/SportsbookBFFLambda/lambda.zip
      Handler: "SportsbookBFFHandler"
      Runtime: provided
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref APIGateway
