import Foundation

public enum BetType: String, CaseIterable, Codable {

    case single = "SINGLE"
    case double = "DOUBLE"
    case treble = "TREBLE"
    case fourFold = "FOURFOLD"
    case fiveFold = "FIVEFOLD"
    case sixFold = "SIXFOLD"
    case sevenFold = "SEVENFOLD"
    case eightFold = "EIGHTFOLD"
    case nineFold = "NINEFOLD"
    case tenFold = "TENFOLD"
    case elevenFold = "ELEVENFOLD"
    case twelveFold = "TWELVEFOLD"
    case thirteenFold = "THIRTEENFOLD"
    case fourteenFold = "FOURTEENFOLD"
    case fifteenFold = "FIFTEENFOLD"
    case sixteenFold = "SIXTEENFOLD"
    case seventeenFold = "SEVENTEENFOLD"
    case eighteenFold = "EIGHTEENFOLD"
    case mineteenFold = "NINETEENFOLD"
    case twentyFold = "TWENTYFOLD"
    case twentyOneFold = "TWENTYONEFOLD"
    case twentyTwoFold = "TWENTYTWOFOLD"
    case twentyThreeFold = "TWENTYTHREEFOLD"
    case twentyFourFold = "TWENTYFOURFOLD"
    case twentyFiveFold = "TWENTYFIVEFOLD"
    case trixie = "TRIXIE"
    case patent = "PATENT"
    case yankee = "YANKEE"
    case canadian = "CANADIAN"
    case heinz = "HEINZ"
    case superHeinz = "SUPER_HEINZ"
    case goliath = "GOLIATH"
    case lucky15 = "LUCKY_15"
    case lucky31 = "LUCKY_31"
    case lucky63 = "LUCKY_63"

}
