name: Mainline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-build:
    name: Build and Test
    runs-on: ubuntu-latest
    container:
      image: swift:5.5.2-focal
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache SPM
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: swift build --build-tests

      - name: Test
        run: swift test --skip-build --parallel
